Monthly_income = int(input("Enter your monthly income"))
Monthly_expenses = int(input("Enter your monthly expenses"))
Monthly_savings = (Monthly_income - Monthly_expenses)
Interest = (Monthly_savings * 12 * 0.05)
Projected_savings = (Monthly_savings * 12 + (Monthly_savings * 12 * 0.05))